hp <- read.table("household_power_consumption.txt", header=TRUE, sep=';', na.strings='?',nrows=1000000, stringsAsFactors=TRUE)
hp$DateTime <- paste(hp$Date, hp$Time)
hp$DateTime <- as.Date(hp$DateTime, format = "%d/%m/%Y %H:%M:%S")
hp_req <- subset(hp, DateTime > "2007-02-01" & DateTime <= "2007-02-02")
hp_req$Day<-as.POSIXlt(paste(hp_req$Date, hp_req$Time), format = "%d/%m/%Y %T"
hp_req$week <- weekdays(hp_req$Day, abbreviate=TRUE)
hp_req_thu<- subset(hp_req, week="Thu")
hp_req_fri<- subset(hp_req, week="Fri")
hp_req_sat<- subset(hp_req, week="Sat")
hp_req_days<- rbind(hp_Req_thu, hp_req_fri, hp_req_sat)
plot(hp_req_days$Global_active_power, type="l",xlab="",ylab="Global Active Power(Kilowatts)",xaxt="n")
axis(1,at=c("0","1500","3000"), labels=c("Thu", "Fri", "Sat"))
dev.copy(png,"plot2.png")
dev.off()